services:
  web:
    container_name: agenda_tec
    restart: always
    build: .
    image: agenda-tec-image
    expose:
      - "8000"
    environment:
      - TINI_SUBREAPER=1
      - DJANGO_HOST=${DJANGO_HOST}
      - DJANGO_PORT=8000
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: ["sh", "-c", "python3 manage.py runserver $DJANGO_HOST:$DJANGO_PORT"]
    volumes:
      - .:/app
    init: true
    depends_on:
      - db
      - redis
    networks:
      - web

  db:
    image: postgres:15
    container_name: agenda_tec_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always
    ports:
      - "${WAHA_PORT}:3000"
    environment:
      WAHA_HTTP_BIND_ADDRESS: "0.0.0.0"
      WAHA_API_KEY: "${WAHA_API_KEY}"
      WAHA_DASHBOARD_USERNAME: "${WAHA_DASHBOARD_USER}"
      WAHA_DASHBOARD_PASSWORD: "${WAHA_DASHBOARD_PASS}"
      WHATSAPP_SWAGGER_USERNAME: "${WAHA_SWAGGER_USER}"
      WHATSAPP_SWAGGER_PASSWORD: "${WAHA_SWAGGER_PASS}"
      WAHA_PRINT_QR: "${WAHA_PRINT_QR}"
      WAHA_LOG_LEVEL: "${WAHA_LOG_LEVEL}"
      WHATSAPP_DEFAULT_ENGINE: "WEBJS"
      WHATSAPP_START_SESSION: "default"
      WHATSAPP_RESTART_ALL_SESSIONS: "true"
      WHATSAPP_SESSIONS_ON_INIT: "default"
      WAHA_BASE_URL: "https://teste.agendatec.faculdadedombosco.net.br"
    volumes:
      - waha_data:/app/.waha
    networks:
      - web

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - web

  celery_worker:
    build: .
    command: celery -A core worker -l info
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - WAHA_API_KEY=${WAHA_API_KEY}
    depends_on:
      - redis
      - db
    networks:
      - web

  celery_beat:
    build: .
    command: celery -A core beat -l info
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - WAHA_API_KEY=${WAHA_API_KEY}
    depends_on:
      - redis
      - db
    networks:
      - web

  caddy:
    image: caddy:2-alpine
    restart: always
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data # Armazena os certificados TLS
      - caddy_config:/config
      - ./logs/caddy:/data/logs
    networks:
      - web

networks:
  web:

volumes:
  pgdata:
  waha_data:
  caddy_data:
  caddy_config:
