services:
  web:
    container_name: agenda_tec
    build: .
    image: agenda-tec-image
    ports:
      - "${DJANGO_PORT}:8000"
    environment:
      - TINI_SUBREAPER=1
      - DJANGO_HOST=${DJANGO_HOST}
      - DJANGO_PORT=8000
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: ["sh", "-c", "python3 manage.py runserver $DJANGO_HOST:$DJANGO_PORT"]
    volumes:
      - .:/app
    init: true
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: agenda_tec_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
