services:
  web:
    container_name: agenda_tec
    build: .
    image: agenda-tec-image
    ports:
      - "${DJANGO_PORT}:8000"
    environment:
      - TINI_SUBREAPER=1
      - DJANGO_HOST=${DJANGO_HOST}
      - DJANGO_PORT=8000
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: ["sh", "-c", "python3 manage.py runserver $DJANGO_HOST:$DJANGO_PORT"]
    volumes:
      - .:/app
    init: true
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: agenda_tec_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always
    ports:
      - "${WAHA_PORT}:3000"
    environment:
      WAHA_HTTP_BIND_ADDRESS: "0.0.0.0"
      WAHA_API_KEY: "${WAHA_API_KEY}"
      WAHA_DASHBOARD_USERNAME: "${WAHA_DASHBOARD_USER}"
      WAHA_DASHBOARD_PASSWORD: "${WAHA_DASHBOARD_PASS}"
      WHATSAPP_SWAGGER_USERNAME: "${WAHA_SWAGGER_USER}"
      WHATSAPP_SWAGGER_PASSWORD: "${WAHA_SWAGGER_PASS}"
      WAHA_PRINT_QR: "${WAHA_PRINT_QR}"
      WAHA_LOG_LEVEL: "${WAHA_LOG_LEVEL}"
      WHATSAPP_DEFAULT_ENGINE: "WEBJS"
      WHATSAPP_START_SESSION: "default"
      WHATSAPP_RESTART_ALL_SESSIONS: "true"
      WHATSAPP_SESSIONS_ON_INIT: "default"
    volumes:
      - waha_data:/app/.waha

volumes:
  pgdata:
  waha_data:
