# Generated by Django 4.2.27 on 2026-01-31 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarModelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Calendário',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.discipline', verbose_name='Disciplina')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('student', 'discipline')},
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='students',
            field=models.ManyToManyField(related_name='disciplines', through='event.Registration', to=settings.AUTH_USER_MODEL, verbose_name='Disciplinas'),
        ),
    ]
