# Generated by Django 4.2.30 on 2026-05-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_calendarmodelview_registration_discipline_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_local',
            field=models.TextField(verbose_name='Local do evento'),
        ),
    ]
