# Generated by Django 4.2.30 on 2026-05-31 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_event_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas cadastradas'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Disciplinas do semestre'},
        ),
    ]
