# Generated by Django 4.2.30 on 2026-09-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_discipline_options_alter_registration_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_active',
        ),
    ]
