# Generated by Django 4.2.30 on 2026-10-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_discipline_is_active_remove_event_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='code',
            field=models.CharField(blank=True, help_text='Código da GVDASA (campo "Descricao"). Identifica a disciplina de forma estável, mesmo se o nome mudar.', max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
    ]
