# Generated by Django 4.2.29 on 2026-04-12 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('matriz_ads', 'Matriz Curricular - ADS'), ('matriz_si', 'Matriz Curricular - SI'), ('horas_comp', 'Horas Complementares'), ('info_inst', 'Informações Institucionais')], max_length=30, verbose_name='Categoria')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='academico/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
    ]
