# Generated by Django 4.2.29 on 2026-04-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccontent',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='academic_files/'),
        ),
    ]
