# Generated by Django 4.2.29 on 2026-04-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_academiccontent_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Respota')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.RemoveField(
            model_name='academiccontent',
            name='created_by',
        ),
    ]
