# Generated by Django 4.2.30 on 2026-04-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_academicfaq_remove_academiccontent_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('contract_type', models.CharField(choices=[('internship', 'Estágio'), ('effective', 'Efetivo')], max_length=30, verbose_name='Tipo do Contrato')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Vagas',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.AlterModelOptions(
            name='academiccontent',
            options={'verbose_name': 'Conteúdo Acadêmico', 'verbose_name_plural': 'Conteúdo Acadêmico'},
        ),
        migrations.AlterModelOptions(
            name='academicfaq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
    ]
