# Generated by Django 4.2.30 on 2026-05-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_joboportunity_alter_academiccontent_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOportunity',
            new_name='JobOpportunity',
        ),
        migrations.AlterField(
            model_name='academicfaq',
            name='answer',
            field=models.TextField(verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='academicfaq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
