# Generated by Django 4.2.30 on 2026-09-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_rename_joboportunity_jobopportunity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccontent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='academicfaq',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='is_active',
        ),
    ]
