# Generated by Django 4.2.30 on 2026-10-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_remove_academiccontent_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccontent',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='academic_files/', verbose_name='Arquivo'),
        ),
    ]
